knp_snappy:
    pdf:
        enabled: true
        binary: /usr/local/bin/wkhtmltopdf
        options:
            page-size: Letter
            margin-top: 10
            margin-right: 10
            margin-bottom: 10
            margin-left: 10