nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:3000', 'https://zestful-nature-production-b23c.up.railway.app']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization', 'Accept']
        max_age: 3600