<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260301184018 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE invoice_items ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE invoice_items ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE invoice_items ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE invoice_items ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE invoice_items ALTER invoice_id SET NOT NULL');
        $this->addSql('ALTER TABLE invoice_items ALTER quantity DROP DEFAULT');
        $this->addSql('ALTER TABLE invoice_items ALTER price DROP DEFAULT');
        $this->addSql('ALTER TABLE invoice_items ALTER tax_rate DROP DEFAULT');
        $this->addSql('ALTER TABLE invoice_items ALTER tax_rate SET NOT NULL');
        $this->addSql('ALTER TABLE invoice_items ALTER discount DROP DEFAULT');
        $this->addSql('ALTER TABLE invoice_items ALTER discount SET NOT NULL');
        $this->addSql('ALTER TABLE invoice_items ALTER subtotal DROP DEFAULT');
        $this->addSql('ALTER TABLE invoice_items ALTER subtotal SET NOT NULL');
        $this->addSql('ALTER TABLE invoice_items ALTER tax_amount DROP DEFAULT');
        $this->addSql('ALTER TABLE invoice_items ALTER tax_amount SET NOT NULL');
        $this->addSql('ALTER TABLE invoice_items ALTER discount_amount DROP DEFAULT');
        $this->addSql('ALTER TABLE invoice_items ALTER discount_amount SET NOT NULL');
        $this->addSql('ALTER TABLE invoice_items ALTER total DROP DEFAULT');
        $this->addSql('ALTER TABLE invoice_items ALTER total SET NOT NULL');
        $this->addSql('ALTER INDEX idx_invoice_items_invoice RENAME TO IDX_DCC4B9F82989F1FD');
        $this->addSql('DROP INDEX idx_invoices_number');
        $this->addSql('ALTER TABLE invoices ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE invoices ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE invoices ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE invoices ALTER currency DROP DEFAULT');
        $this->addSql('ALTER TABLE invoices ALTER currency SET NOT NULL');
        $this->addSql('ALTER TABLE invoices ALTER subtotal DROP DEFAULT');
        $this->addSql('ALTER TABLE invoices ALTER subtotal SET NOT NULL');
        $this->addSql('ALTER TABLE invoices ALTER total_tax DROP DEFAULT');
        $this->addSql('ALTER TABLE invoices ALTER total_tax SET NOT NULL');
        $this->addSql('ALTER TABLE invoices ALTER total_discount DROP DEFAULT');
        $this->addSql('ALTER TABLE invoices ALTER total_discount SET NOT NULL');
        $this->addSql('ALTER TABLE invoices ALTER grand_total DROP DEFAULT');
        $this->addSql('ALTER TABLE invoices ALTER grand_total SET NOT NULL');
        $this->addSql('ALTER TABLE invoices ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE invoices ALTER created_at SET NOT NULL');
        $this->addSql('ALTER INDEX invoices_invoice_number_key RENAME TO UNIQ_6A2F2F952DA68207');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE invoice_items DROP created_at');
        $this->addSql('ALTER TABLE invoice_items DROP updated_at');
        $this->addSql('ALTER TABLE invoice_items ALTER id SET DEFAULT nextval(\'invoice_items_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE invoice_items ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE invoice_items ALTER quantity SET DEFAULT 1');
        $this->addSql('ALTER TABLE invoice_items ALTER price SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE invoice_items ALTER tax_rate SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE invoice_items ALTER tax_rate DROP NOT NULL');
        $this->addSql('ALTER TABLE invoice_items ALTER discount SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE invoice_items ALTER discount DROP NOT NULL');
        $this->addSql('ALTER TABLE invoice_items ALTER subtotal SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE invoice_items ALTER subtotal DROP NOT NULL');
        $this->addSql('ALTER TABLE invoice_items ALTER tax_amount SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE invoice_items ALTER tax_amount DROP NOT NULL');
        $this->addSql('ALTER TABLE invoice_items ALTER discount_amount SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE invoice_items ALTER discount_amount DROP NOT NULL');
        $this->addSql('ALTER TABLE invoice_items ALTER total SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE invoice_items ALTER total DROP NOT NULL');
        $this->addSql('ALTER TABLE invoice_items ALTER invoice_id DROP NOT NULL');
        $this->addSql('ALTER INDEX idx_dcc4b9f82989f1fd RENAME TO idx_invoice_items_invoice');
        $this->addSql('ALTER TABLE invoices DROP updated_at');
        $this->addSql('ALTER TABLE invoices ALTER id SET DEFAULT nextval(\'invoices_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE invoices ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE invoices ALTER currency SET DEFAULT \'MXN\'');
        $this->addSql('ALTER TABLE invoices ALTER currency DROP NOT NULL');
        $this->addSql('ALTER TABLE invoices ALTER subtotal SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE invoices ALTER subtotal DROP NOT NULL');
        $this->addSql('ALTER TABLE invoices ALTER total_tax SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE invoices ALTER total_tax DROP NOT NULL');
        $this->addSql('ALTER TABLE invoices ALTER total_discount SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE invoices ALTER total_discount DROP NOT NULL');
        $this->addSql('ALTER TABLE invoices ALTER grand_total SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE invoices ALTER grand_total DROP NOT NULL');
        $this->addSql('ALTER TABLE invoices ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE invoices ALTER created_at DROP NOT NULL');
        $this->addSql('CREATE INDEX idx_invoices_number ON invoices (invoice_number)');
        $this->addSql('ALTER INDEX uniq_6a2f2f952da68207 RENAME TO invoices_invoice_number_key');
    }
}
